"""
A temporary module to deal with organization of high-level functions that lead
to circular imports.
"""
from astropy.table import Table
from astropy import units
from IPython import embed
import numpy as np

from pypeit import io
from pypeit import onespec
from pypeit import PypeItError
from pypeit import specobj
from pypeit import specobjs
from pypeit import utils
from pypeit.core import spectrum
from pypeit.core import wave
from pypeit.spectrographs.util import load_spectrograph


def load_spectra(specfile, extract=None, fluxed=False, chk_version=True):
    """
    Read a spec1d or onespec file.

    Parameters
    ----------
    specfile : :obj:`str`
        File with the data
    extract : str, optional
        The extraction used to produce the spectrum.  Must be either None,
        ``'BOX'`` (for a boxcar extraction), or ``'OPT'`` for optimal
        extraction.  If None, the optimal extraction will be returned, if it
        exists, otherwise the boxcar extraction will be returned.  Only relevant
        if the input is a spec1d file.
    fluxed : bool, optional
        If True, return the flux-calibrated spectrum, if it exists.  If the flux
        calibration hasn't been performed or ``fluxed=False``, the spectrum is
        returned in counts.  Only relevant if the input is a spec1d file.
    chk_version : :obj:`bool`, optional
        When reading in existing files written by PypeIt, perform strict
        version checking to ensure a valid file.  If False, the code will
        try to keep going, but this may lead to faults and quiet failures.
        User beware!

    Returns
    -------
    :class:`astropy.io.fits.Header`:
        The primary header of the input file.
    list:
        List of :class:`~pypeit.core.spectrum.Spectrum` objects.
    """

    # TODO: Can we use try/except blocks to avoid opening the fits file?

    # Load a OneSpec file
    hdu = io.fits_open(specfile)
    is_onespec = 'DMODCLS' in hdu[1].header and hdu[1].header['DMODCLS'] == 'OneSpec'
    hdu.close()
    if is_onespec:
        spec = onespec.OneSpec.from_file(specfile, chk_version=chk_version)

        # TODO: I'm not sure which wavelength vector to use, but allowing data
        # with wave==0 wreaks havoc later on, so I deal with it here.
        _wave = spec.wave
        _gpm = spec.mask.astype(bool)
        bad_wave = _wave == 0
        if np.any(bad_wave):
            if np.any(bad_wave & _gpm):
                raise PypeItError(
                    'The input spectrum has unmasked pixels with the wavelength set to zero.'
                )
            if spec.wave_grid_mid is None:
                raise PypeItError(
                    'The input spectrum has pixels with the wavelength set to zero and no '
                    'alternative wavelength grid to use.'
                )
            _wave[bad_wave] = spec.wave_grid_mid[bad_wave]

        return spec.head0, [spectrum.Spectrum(
            _wave, spec.flux, ivar=spec.ivar, gpm=_gpm, meta=spec.spect_meta
        )]

    # Load a spec1d file
    sobjs = specobjs.SpecObjs.from_fitsfile(specfile, chk_version=chk_version)
    return sobjs.header, specobjs_to_spectrum(sobjs, extract=extract, fluxed=fluxed)


# TODO: This could possibly be a member function of pypeit.specobjs.SpecObjs.
def specobjs_to_spectrum(sobjs, extract=None, fluxed=False):
    """
    Utility function to convert a :class:`~pypeit.specobjs.SpecObjs` object into
    a list of :class:`~pypeit.core.spectrum.Spectrum` objects.

    Parameters
    ----------
    sobjs : :class:`~pypeit.specobjs.SpecObjs`
        Object with extracted 1D spectra
    extract : :obj:`str`, optional
        The type of extraction to use.  Options are 'OPT' for optimal extraction or
        'BOX' for boxcar extraction.
    fluxed : :obj:`bool`, optional
        If True, return the flux-calibrated spectrum.  If False, return the
        uncalibrated counts.

    Returns
    -------
    list
        List of :class:`~pypeit.core.spectrum.Spectrum` objects with the
        extracted spectra.
    """

    # Get the metadata
    meta_spec = load_spectrograph(sobjs.header['PYP_SPEC']).parse_spec_header(sobjs.header)

    # Build up the list of spectra
    spectra = []
    for sobj in sobjs:
        ext, cal = sobj.best_ext_match(extract=extract, fluxed=fluxed)
        func = sobj.get_box_ext if ext == 'BOX' else sobj.get_opt_ext
        wave, flux, ivar, gpm = func(fluxed=cal)
        # TODO: Deal with wave=0 data?
        spectra += [spectrum.Spectrum(wave, flux, ivar=ivar, gpm=gpm, meta=meta_spec)]
    return spectra


def load_wmko_std_spectrum(fits_file:str, outfile=None, pad=False, split=True):
    """
    Load a standard spectrum generated by WMKO IDL scripts of the great Greg
    Wirth.

    The SpecObjs generated is checked that it is ready for fluxing

    Parameters
    ----------
    fits_file : str
        filename
    outfile : str, optional
        Write the SpecObjs object to this FITS file.
    pad : bool, optional
        True if the resulting SpecObjs should be padded to an even length.
    split : bool,optional
        True if the resulting SpecObjs should be split into two detectors, False
        if it should be treated as a mosaic.

    Returns
    -------
    :class:`~pypeit.specobjs.SpecObjs`
        Object holding the spectra
    """

    # Open up
    hdul = io.fits_open(fits_file)
    meta = Table(hdul[1].data)
    idl_spec = Table(hdul[2].data)

    # Hope this always works..
    if split:
        npix = int(len(idl_spec)/2)
    else:
        npix = len(idl_spec)

    if pad:
        if int(len(idl_spec)) % 2 != 0:
            npix = int((len(idl_spec)+1)/2)
            idl_spec.add_row([0.0, 0.0])

    # Generate vacuum wavelengths
    idl_vac = wave.airtovac(idl_spec['WAVELENGTH']*units.AA)

    # Generate SpecObj
    if not split:
        sobj1 = specobj.SpecObj.from_arrays('MultiSlit', idl_vac.value[0:npix],
                                            idl_spec['COUNTS'].data[0:npix],
                                            1./(idl_spec['COUNTS'].data[0:npix]),
                                            np.ones(idl_spec['COUNTS'].data[0:npix].size),
                                            DET='MSC03')
    else:
        sobj1 = specobj.SpecObj.from_arrays('MultiSlit', idl_vac.value[0:npix],
                                            idl_spec['COUNTS'].data[0:npix],
                                            1./(idl_spec['COUNTS'].data[0:npix]),
                                            np.ones(idl_spec['COUNTS'].data[0:npix].size),
                                            DET='DET03')
        
        sobj2 = specobj.SpecObj.from_arrays('MultiSlit', idl_vac.value[npix:],
                                            idl_spec['COUNTS'].data[npix:],
                                            1./(idl_spec['COUNTS'].data[npix:]),
                                            np.ones(idl_spec['COUNTS'].data[npix:].size),
                                            DET='DET07')

    # SpecObjs
    sobjs = specobjs.SpecObjs()
    sobjs.add_sobj(sobj1)
    if split:
        sobjs.add_sobj(sobj2)

    # Fill in header
    coord = utils.radec_to_coord((meta['RA'][0], meta['DEC'][0]))
    sobjs.header = dict(EXPTIME=1., 
                        AIRMASS=float(meta['AIRMASS'][0]), 
                        DISPNAME=str(meta['GRATING'][0]), 
                        SLMSKNAM='', # No slitmask is used for the throughput data
                        PYP_SPEC='keck_deimos', 
                        PYPELINE='MultiSlit',
                        BINNING=f'{meta["SPEC_BIN"][0]},{meta["SPEC_BIN"][0]}',
                        RA=coord.ra.deg, 
                        DEC=coord.dec.deg
                   )

    # Check
    assert sobjs.ready_for_fluxing()

    # Write?
    if outfile is not None:
        sobjs.write_to_fits(sobjs.header, outfile)
        print("Wrote: {}".format(outfile))

    return sobjs
